DROP TABLE IF EXISTS "public"."rag_prompt_configurations";
CREATE TABLE "public"."rag_prompt_configurations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  "name" varchar(128) NOT NULL UNIQUE,
  "prompt" TEXT NOT NULL UNIQUE,

    -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
)
;



-- ----------------------------
-- Table structure for rag_model
-- ----------------------------
DROP TABLE IF EXISTS "public"."rag_model";
CREATE TABLE "public"."rag_model" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  "ip" varchar(128)  NOT NULL,
  "port" varchar(128) NOT NULL,
  "name" varchar(128) NOT NULL UNIQUE,

    -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
)
;



-- ----------------------------
-- Table structure for rag_document_elements
-- ----------------------------
DROP TABLE IF EXISTS "public"."rag_document_elements";
CREATE TABLE "public"."rag_document_elements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  "book_id" BIGINT NOT NULL,
  "doc_type" varchar(128)  NOT NULL,
  "content" text ,
  "text_level" BIGINT,
  "caption" text ,
  "footnote" text ,
  "text_format" varchar(20) ,
  "img_path" text ,
  "page_idx" BIGINT NOT NULL,

    -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
)
;


DROP TABLE IF EXISTS "public"."rag_book";
CREATE TABLE "public"."rag_book" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  "name" varchar(128) NOT NULL UNIQUE,

    -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
)
;




DROP TABLE IF EXISTS "public"."rag_optimized_content";
CREATE TABLE "public"."rag_optimized_content" (
  -- 主键
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  
  -- 业务字段
  "book_id" BIGINT NOT NULL,
  "page_idx" INTEGER NOT NULL,
  "content" TEXT,
  "corrections" TEXT,
  "model_name" VARCHAR(128) NOT NULL,
  "format_json" TEXT,
  
    -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL
);